### ISSUE TITLE
No example data

### ISSUE THREAD

**Issue by ahrobinson** [PredixDev/px-vis-pie-chart#13]
There is no example data showing the type of data that this element expects, on the Predix-UI page. Thanks.

**Comment by benoitjchevalier** [comment]
Hello,

thanks for the feedback, we're looking at how we can improve all the charts demo to include some explanation on the data format.

For the pie chart the current data used in the demo look like that:
[{
    "x": 15,
    "y": "IPA"
}, {
    "x": 1,
    "y": "Pils"
}, {
    "x": 1,
    "y": "Lager"
}, {
    "x": 8,
    "y": "Lambic"
}, {
    "x": 12,
    "y": "Stout"
},
{
    "x": 7,
    "y": "Pale Ale"
},
{
    "x": 9,
    "y": "Porter"
},
{
    "x": 4,
    "y": "Heffeweisse"
}]

I hope that helps for now.

I'll close this when we have improved our demos.

Cheers,
Ben

**Comment by benoitjchevalier** [comment]
data can now be seen in the demo on www.predix-ui.com

**Comment by bandarumurali** [comment]
Hi @benoitjchevalier ,
Where can we find the exact chart data that we need to pass to render the chart? Here is the data which I have mentioned in the predix ui site for rendering the chart

[{
  "percentage": **"26.5"**,
  "x": 15,
  "y": "IPA",
  "colorIndex": 0,
  "backgroundColor": "rgb(93,165,218)"
}, {
  "percentage": **"1.5"**,
  "x": 1,
  "y": "Pils",
  "colorIndex": 1,
  "backgroundColor": "rgb(250,164,58)"
}, {
  "percentage": **"2.75"**,
  "x": 1,
  "y": "Lager",
  "colorIndex": 2,
  "backgroundColor": "rgb(96,189,104)"
}, {
  "percentage": **"13.25"**,
  "x": 8,
  "y": "Lambic",
  "colorIndex": 3,
  "backgroundColor": "rgb(241,124,176)"
}, {
  "percentage": "21",
  "x": 12,
  "y": "Stout",
  "colorIndex": 4,
  "backgroundColor": "rgb(178,145,47)"
}, {
  "percentage": "12",
  "x": 7,
  "y": "Pale Ale",
  "colorIndex": 5,
  "backgroundColor": "rgb(178,118,178)"
}, {
  "percentage": "16",
  "x": 9,
  "y": "Porter",
  "colorIndex": 6,
  "backgroundColor": "rgb(222,207,63)"
}, {
  "percentage": "7",
  "x": 4,
  "y": "Heffeweisse",
  "colorIndex": 7,
  "backgroundColor": "rgb(241,88,84)"
}]

When the chart is rendered based on the percentage, the data is automatically converted as below in which values I have mentioned are modified
[{"percentage":"**26.32**","x":15,"y":"IPA","colorIndex":0,"backgroundColor":"rgb(93,165,218)"},{"percentage":"**1.75**","x":1,"y":"Pils","colorIndex":1,"backgroundColor":"rgb(250,164,58)"},{"percentage":"**1.75**","x":1,"y":"Lager","colorIndex":2,"backgroundColor":"rgb(96,189,104)"},{"percentage":"**14.04**","x":8,"y":"Lambic","colorIndex":3,"backgroundColor":"rgb(241,124,176)"},{"percentage":"**21.05**","x":12,"y":"Stout","colorIndex":4,"backgroundColor":"rgb(178,145,47)"},{"percentage":"**12.28**","x":7,"y":"Pale Ale","colorIndex":5,"backgroundColor":"rgb(178,118,178)"},{"percentage":"**15.79**","x":9,"y":"Porter","colorIndex":6,"backgroundColor":"rgb(222,207,63)"},{"percentage":"**7.02**","x":4,"y":"Heffeweisse","colorIndex":7,"backgroundColor":"rgb(241,88,84)"}].

By debugging I have found that the value of percentage will be dependent on the x parameter that is specified in the chart data. Can you please help me what value needs to be passed to x parameter so that the percentages are rendered in the chart exactly asI have mentioned? I have gone through whole document but didn't find what value will be passed as x parameter.
