### ISSUE TITLE
Is there a way to get the data when you click a piece of the pie chart? 

### ISSUE THREAD

**Issue by ahrobinson** [PredixDev/px-vis-pie-chart#14]
I am looking for a way to capture the data when I click on a particular piece of the pie chart. So if there is a portion that has a Title of Europe and Message of 23, I wnt to be able to capture that data. Thanks!

**Comment by benoitjchevalier** [comment]
There isn't a way to do this at the moment. However this would be a fairly trivial change, we would need to:
- create a new function that would replace the one called on tap [here](https://github.com/PredixDev/px-vis/blob/master/px-vis-pie.html#L353)
- That new function should fire a "px-vis-pie-slice-clicked" with the title and value (using the same mechanism as [here](https://github.com/PredixDev/px-vis/blob/master/px-vis-pie.html#L465) )
- Call [_centerOnSlice](https://github.com/PredixDev/px-vis/blob/master/px-vis-pie.html#L452), ideally modifying it so it accepts the title and value previously calculated rather than re-calculating it

And then add a unit test for it.

We're always happy to take pull requests ;)

**Comment by ahrobinson** [comment]
Awesome thanks for the help!
